{{- $name := include "apigwww.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "ocelot-{{ $name }}"
  labels:
    app: {{ template "apigwww.name" . }}
    chart: {{ template "apigwww.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ (.Files.Glob "configuration-web-whiskyarchive.json").AsConfig | indent 2 -}} 

