{{- $name := include "identity-api.fullname" . -}}
{{- $sqlsrv := include "sql-name" . -}}
{{- $mvc_url := include "url-of" (list .Values.app.ingress.entries.mvc  .) -}}
{{- $whiskyrecording_url := include "url-of" (list .Values.app.ingress.entries.whiskyrecording .) -}}
{{- $webwhiskyarchiveagg := include "url-of" (list .Values.app.ingress.entries.webwhiskyarchiveagg .) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "identity-api.name" . }}
    chart: {{ template "identity-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  identity__ConnectionString: Server={{ $sqlsrv }};Initial Catalog={{ .Values.inf.sql.identity.db }};User Id={{ .Values.inf.sql.common.user }};Password={{ .Values.inf.sql.common.pwd }};
  mvc_e: http://{{ $mvc_url }}
  whiskyrecording_e: http://{{ $whiskyrecording_url }}
  webwhiskyarchiveagg_e: http://{{ $webwhiskyarchiveagg }}
  internalurls__apigwww__hc: http://{{ .Values.app.svc.webwhiskyarchiveapigw }}/hc
  internalurls__identity__hc: http://{{ .Values.app.svc.identity }}/hc
  internalurls__whiskyrecording__hc: http://{{ .Values.app.svc.whiskyrecording }}/hc
  enableDevspaces: "{{ .Values.enableDevspaces }}"