apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sql-data
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whiskyarchive
        component: sql-data
    spec:
      containers:
      - name: sql-data
        image: microsoft/mssql-server-linux:2017-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: Developer
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-whiskyarchive
              key: SA_PASSWORD
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: whiskyarchive-sql-disk