apiVersion: v1
kind: Service
metadata:
  labels:
    app: whiskyarchive
    component: sql-data
  name: sql-data
spec:
  ports:
  - port: 1433
  selector:
    app: whiskyarchive
    component: sql-data