apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app: whiskyarchive
  name: whiskyarchive-webmvc-loopback
  namespace: default
spec:
  rules:
  - http: 
      paths:
      - backend:
          serviceName: webmvc
          servicePort: http
        path: /webmvc
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app: whiskyarchive
  name: whiskyarchive-identity-api-loopback
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: identity
          servicePort: http
        path: /identity