replicaCount: 1
clusterName: whiskyarchive
pathBase: /webmvc

image:
  repository: blockchain0026/webmvc
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: UseLoadTest
      key: all_EnableLoadTest
    - name: WhiskyArchiveUrl
      key: internalurls__apigwww
    - name: ExternalWhiskyArchiveUrl
      key: urls__apigwww
    - name: CallBackUrl
      key: urls__mvc
    - name: IdentityUrl
      key: urls__IdentityUrl
    - name: WhiskyArchiveUrlHC
      key: internalurls__apigwww__hc
    - name: IdentityUrlHC
      key: internalurls__identity__hc
    - name: WhiskyRecordingUrlHC
      key: internalurls__whiskyrecording__hc
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OrchestratorType
      value: 'K8S'
    - name: IsClusterEnv
      value: 'True'

